easy_admin:
  # BASIC CONFIG : https://symfony.com/doc/master/bundles/EasyAdminBundle/book/basic-configuration.html
  #sitename: 'Admin ResumeMe Website'
  entities:
      resumeMe:
        class: App\Entity\ResumeMe
        form:
          fields:
            - { type: 'group' , columns: 8,  label: 'Basic Information' }
            - firstname
            - lastname
            - city
            - postal_code
            - { type: 'group' , columns: 4,  label: 'Image of profile' }
            - { property: 'imageFile', type: 'vich_image' }
            - { type: 'group' , columns: 8,  label: 'Contact informations' }
            - email
            - phone
            - { type: 'group' , columns: 4,  label: 'Advanced options' }
            - available





        list:
          fields:
            - { property: 'filename', type: 'image', base_path: '%app.path.resume_image%', label: 'Profile image' }
            - firstname
            - lastname
            - available
        show:
          fields:
            - { property: 'filename', type: 'image', base_path: '%app.path.resume_image%' }


