easy_admin:
  # BASIC CONFIG : https://symfony.com/doc/master/bundles/EasyAdminBundle/book/basic-configuration.html
  #sitename: 'Admin ResumeMe Website'

  #ROUTE ACTION :
  #https://symfony.com/doc/master/bundles/EasyAdminBundle/tutorials/custom-actions.html#route-based-actions

  #SEPARATE CODE :
  #https://symfony.com/doc/master/bundles/EasyAdminBundle/tutorials/complex-backend-config.html
  design:
    assets:
      # all kinds of assets are supported and linked accordingly
      css:
        - 'build/ea_custom.css'
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
    menu:
      - { label: 'Summary', route: 'summary_resume', params: { id: 1 }, default: false}
      - { label: 'Me', entity: 'resumeMe' }
      - { label: 'Works', entity: 'works' }
      - { label: 'Formations', entity: 'Formations' }
      - { label: 'Technos', entity: 'Technos'}
      - { label: 'Blog', entity: 'Articles'}

  entities:
      resumeMe:
        class: App\Entity\ResumeMe
        form:
          fields:
            - { type: 'group' , columns: 8,  label: 'Basic Information' }
            - { property: 'firstname', columns: 6}
            - { property: 'lastname', columns: 6}
            - { property: 'profession', columns: 12, css_class: 'mwFormEdit'}
            - { property: 'intro_carrer', columns: 12, type_option: 'text', css_class: 'mwFormEdit'}

            - { type: 'section', label: 'Contact', css_class: 'test2', columns: 12}
            - { property: 'email', columns: 6}
            - { property: 'phone', columns: 6}
            - { property: 'city', columns: 6}
            - { property: 'postal_code', columns: 6}
            - available
            - { property: 'interest', type: 'choice', type_options: { expanded: true, choices: [CDI: CDI, CDD: CDD, FREELANCE: FREELANCE] }}
            - { type: 'section', label: 'Social', css_class: 'test2', columns: 12}
            - { property: 'socialLinkedin', columns: 6, label: 'Linkedin'}
            - { property: 'socialGithub', columns: 6, label: 'Github'}
            - { type: 'group' , columns: 4,  label: 'Files' }
            - { property: 'imageFile', type: 'vich_image', help: 'Upload your resume on format PDF' }
            - { type: 'section', label: 'CV format PDF' }
            - { property: 'CvFile', type: 'vich_file', help: 'Upload your pictures for resume' }
        list:
          fields:
            - ID
            - { property: 'filename', type: 'image', base_path: '%app.path.resume_image%', label: 'Profile image' }
            - firstname
            - lastname
            - available
            - { property: 'CvFile', template: 'cvFile.html.twig', base_path: '%app.path.resume_cv%' }
        show:
          fields:
            - { property: 'filename', type: 'image', base_path: '%app.path.resume_image%' }
      works:
        class: App\Entity\Works
        form:
          fields:
            - currentWork
            - {property: 'Title', type: 'text'}
            - {property: 'Company', type: 'text'}
            - Description
            - {property: 'City', type: 'text'}
            - {property: 'start_at', type: 'date', type_options: { widget: 'single_text' } }
            - {property: 'end_at', type: 'date', type_options: { widget: 'single_text' } }
            - {property: 'resume_me', type: 'entity', type_options: { class: 'App\Entity\ResumeMe', multiple: false } }
            - {property: 'technos', type: 'entity', type_options: { class: 'App\Entity\Technos', multiple: true } }
      Formations:
        class: App\Entity\Formations
        form:
          fields:
            - {property: 'Title', type: 'text'}
            - Description
            - {property: 'Organisation', type: 'text'}
            - {property: 'City', type: 'text'}
            - {property: 'start_at', type: 'date', type_options: { widget: 'single_text' } }
            - {property: 'end_at', type: 'date', type_options: { widget: 'single_text' } }
            - {property: 'resume_me', type: 'entity', type_options: { class: 'App\Entity\ResumeMe', multiple: false } }
      Technos:
        class: App\Entity\Technos
        form:
          fields:
            - {property: 'label', type: 'text'}
        list:
          fields:
            - ID
            - label
      Articles:
        controller: App\Controller\BlogController
        templates:
          edit: 'EasyAdmin/articles/edit.html.twig'
          new: 'EasyAdmin/articles/new.html.twig'
        class: App\Entity\Articles
        list:
          fields:
            - {property: 'ID', label: 'ID'}
            - {property: 'uuid', label: 'Ref.folder'}
            - title
            - isPublished
            - created_at
            - updated_at

        form:
          fields:
            - { property: 'title', type: 'text'}
            - { property: 'body',  type: 'KMS\FroalaEditorBundle\Form\Type\FroalaEditorType', columns: 12}
            - { property: 'coverImageFile', type: 'vich_image', label: 'Profile image' }
            - isPublished


