twig:
    form_themes:
        - '@KMSFroalaEditor/Form/froala_widget.html.twig'

kms_froala_editor:
    language: fr
    toolbarInline: false
    toolbarVisibleWithoutSelection: true
    tableColors: [ "#FFFFFF", "#FF0000" ]
    height: 400
#    width: 700
    zIndex: 0
    pluginsDisabled: [ "save" ]
    charCounterCount: true
    imageAllowedTypes: ['jpeg', 'jpg', 'png']
    # The image upload folder in your /web directory.
    # Default: "/upload".
    imageUploadFolder: "/uploads/blog/"
    #events:
        #keyup: function(keyupEvent) {del();}
        #image.removed: function ($img){ deleteImage(); }


    # The image upload URL base.
    # Usage: if you are using URL rewritting for your assets.
    # Default: same value as provided as folder.
    imageUploadPath: "/uploads/blog"

    includeCodeMirror: false

    # Disable Font Awesome inclusion.
    includeFontAwesome: false

    # Disable all bundle javascripts inclusion (not concerning CodeMirror).
    # Usage: if you are using Grunt or other and you want to include yourself all scripts.
    includeJS: false

    # Disable all bundle CSS inclusion (not concerning Font Awesome nor CodeMirror).
    # Usage: if you are using Grunt or other and you want to include yourself all stylesheets.
    includeCSS: false
    customJS: /build/froala.js


