vich_uploader:
    db_driver: orm

    mappings:
        resume_image:
            uri_prefix: /images/resume
            upload_destination: '%kernel.project_dir%/public/images/resume'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
