vich_uploader:
    db_driver: orm

    mappings:
        resume_image:
            uri_prefix: /uploads/resume
            upload_destination: '%kernel.project_dir%/public/uploads/resume'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        resume_cv:
            uri_prefix: /uploads/resume/cv
            upload_destination: '%kernel.project_dir%/public/uploads/resume/cv'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        articles:
            uri_prefix: /uploads/blog/
            upload_destination: '%kernel.project_dir%/public/uploads/blog'
            namer: Vich\UploaderBundle\Naming\UniqidNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
