vich_uploader:
    db_driver: orm

    mappings:
        resume_image:
            uri_prefix: /uploads/resume
            upload_destination: '%kernel.project_dir%/public/uploads/resume'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        resume_cv:
            uri_prefix: /uploads/resume/cv
            upload_destination: '%kernel.project_dir%/public/uploads/resume/cv'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        articles:
            uri_prefix: /uploads/blog/articles/
            upload_destination: '%kernel.project_dir%/public/uploads/blog/articles/'
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'uuid', transliterate: true} # supposing that the object contains a "slug" attribute or a "getSlug" method
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'uuid'} # supposing that the object contains a "slug" attribute or a "getSlug" method



    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
